from typing import Protocol


class ITokenService(Protocol):
    def create_access_token(self, subject: str, roles: list[str]) -> str: ...
    def create_refresh_token(self, subject: str) -> str: ...
    def decode_token(self, token: str) -> dict: ...
