"""add encrypted_agent_private_key, encryption_iv, last_nonce to accounts

Revision ID: 59cb2fdcde6b
Revises: 8827fb96b216
Create Date: 2026-05-17 00:26:07.922859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59cb2fdcde6b'
down_revision: Union[str, None] = '8827fb96b216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sz_decimals', sa.Integer(), nullable=False),
    sa.Column('is_perp', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('accounts',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_address', sa.String(length=42), nullable=True),
    sa.Column('encrypted_agent_private_key', sa.Text(), nullable=True),
    sa.Column('encryption_iv', sa.String(), nullable=True),
    sa.Column('last_nonce', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.Enum('MASTER', 'SUB_ACCOUNT', 'VAULT', name='account_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('copy_strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_wallet', sa.String(length=42), nullable=False),
    sa.Column('target_wallet', sa.String(length=42), nullable=False),
    sa.Column('direction', sa.Enum('FORWARD', 'REVERSE', name='direction'), nullable=False),
    sa.Column('copy_ratio', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('pnl_control_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_wallet'], ['accounts.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_strategies_target_wallet'), 'copy_strategies', ['target_wallet'], unique=False)
    op.create_index(op.f('ix_copy_strategies_user_wallet'), 'copy_strategies', ['user_wallet'], unique=False)
    op.create_table('cross_asset_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('ref_asset_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Enum('GT', 'LT', name='operator'), nullable=False),
    sa.Column('threshold_px', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ref_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['copy_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_asset_triggers_strategy_id'), 'cross_asset_triggers', ['strategy_id'], unique=False)
    op.create_table('orders',
    sa.Column('oid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('owner_address', sa.String(length=42), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('is_buy', sa.Boolean(), nullable=False),
    sa.Column('limit_px', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('sz', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FILLED', 'CANCELED', 'REJECTED', name='order_status'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['owner_address'], ['accounts.address'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['copy_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_orders_asset_id'), 'orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_orders_owner_address'), 'orders', ['owner_address'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_table('fills',
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.BigInteger(), nullable=False),
    sa.Column('owner_address', sa.String(length=42), nullable=False),
    sa.Column('px', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('sz', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['oid'], ['orders.oid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_address'], ['accounts.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fill_id')
    )
    op.create_index(op.f('ix_fills_oid'), 'fills', ['oid'], unique=False)
    op.create_index(op.f('ix_fills_owner_address'), 'fills', ['owner_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_owner_address'), table_name='fills')
    op.drop_index(op.f('ix_fills_oid'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_owner_address'), table_name='orders')
    op.drop_index(op.f('ix_orders_asset_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cross_asset_triggers_strategy_id'), table_name='cross_asset_triggers')
    op.drop_table('cross_asset_triggers')
    op.drop_index(op.f('ix_copy_strategies_user_wallet'), table_name='copy_strategies')
    op.drop_index(op.f('ix_copy_strategies_target_wallet'), table_name='copy_strategies')
    op.drop_table('copy_strategies')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
